# Generated by Django 5.1.4 on 2024-12-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_userprofile_gender_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
