# Generated by Django 5.1.4 on 2024-12-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0006_rename_name_userprofile_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="destination",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recommendationdata",
            name="destination",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(model_name="weatherflightdata", name="trip",),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weather_data", models.JSONField(blank=True, null=True)),
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_flight_data",
                        to="planner.trip",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Destination",),
        migrations.DeleteModel(name="WeatherFlightData",),
    ]
