# Generated by Django 5.1.4 on 2024-12-11 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0007_alter_trip_destination_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("country", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "climate",
                    models.CharField(
                        choices=[
                            ("tropical", "Tropical"),
                            ("desert", "Desert"),
                            ("temperate", "Temperate"),
                            ("alpine", "Alpine"),
                            ("mediterranean", "Mediterranean"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("beach", "Beach"),
                            ("city", "City"),
                            ("mountains", "Mountains"),
                            ("historical", "Historical"),
                            ("adventure", "Adventure"),
                            ("cultural", "Cultural"),
                            ("nature", "Nature"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("low", "Low (Under $1000)"),
                            ("medium", "Medium ($1000-$3000)"),
                            ("high", "High ($3000-$5000)"),
                            ("luxury", "Luxury (Over $5000)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="userprofile", name="preferences",),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_budget_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low (Under $1000)"),
                    ("medium", "Medium ($1000-$3000)"),
                    ("high", "High ($3000-$5000)"),
                    ("luxury", "Luxury (Over $5000)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beach", "Beach"),
                    ("city", "City"),
                    ("mountains", "Mountains"),
                    ("historical", "Historical"),
                    ("adventure", "Adventure"),
                    ("cultural", "Cultural"),
                    ("nature", "Nature"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_climate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tropical", "Tropical"),
                    ("desert", "Desert"),
                    ("temperate", "Temperate"),
                    ("alpine", "Alpine"),
                    ("mediterranean", "Mediterranean"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recommendationdata",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planner.destination"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips",
                to="planner.destination",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recommendationdata", unique_together={("user", "destination")},
        ),
    ]
