# Generated by Django 5.1.4 on 2024-12-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0008_destination_remove_userprofile_preferences_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="destination", name="image_url",),
        migrations.AlterField(
            model_name="destination",
            name="budget_range",
            field=models.CharField(
                choices=[
                    ("low", "Low (Under Rs. 10000)"),
                    ("medium", "Medium (Rs. 10000-30000)"),
                    ("high", "High (Rs. 30000-80000)"),
                    ("luxury", "Luxury (Over Rs. 80000)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_budget_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low (Under Rs. 10000)"),
                    ("medium", "Medium (Rs. 10000-30000)"),
                    ("high", "High (Rs. 30000-80000)"),
                    ("luxury", "Luxury (Over Rs. 80000)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
