# Generated by Django 5.1.4 on 2024-12-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0013_remove_recommendationdata_rating_delete_weatherdata"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="trip_history",),
    ]
