# Generated by Django 5.1.4 on 2024-12-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0014_remove_userprofile_trip_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="trip_history",
            field=models.ManyToManyField(blank=True, to="planner.trip"),
        ),
    ]
